pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('DockerHub-ID')
        registry = "prasanthrk/e-comm-frontend"
        registrycredentials = 'DockerHUB-ID'
        dockerimage = ''

    }

    stages {
        stage ('docker image build') {
            steps {
                sh 'sudo docker build -t prasanthrk/e-comm-frontend .'
            }
        }

        stage ('docker login') {
            steps {
                 sh 'echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }

    }
}